config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[index show new create destroy]

  # Defines the root path route ("/")
  root "home#index"

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end
  resources :inventories, only: %i[index show new create destroy] do
    resources :inventory_foods, only: %i[new create destroy]
  end
  resources :shopping_lists, only: %i[index]

  get '/public_recipes', to: 'recipes#public_recipes'
end

app/models/inventory.rb
# == Schema Information
#
# Table name: inventories
#
#  id          :bigint           not null, primary key
#  description :text
#  name        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_inventories_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Inventory < ApplicationRecord
  validates :name, presence: true

  belongs_to :user
  has_many :inventory_foods
  validates :description, length: { in: 1..200 }
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @inventories = Inventory.where(user_id: current_user.id)
  end

  def show
    @inventory = Inventory.find_by(id: params[:id])
    @inventory_foods = InventoryFood.where(inventory_id: params[:id]).includes([:food])
  end

  def new
    @inventory = Inventory.new
  end

  def create
    @inventory = Inventory.new(inventory_params)

    if @inventory.save
      redirect_to inventories_path, notice: 'Successfully created Inventory.'
    else
      render :new, alert: 'Could not create inventory.'
    end
  end

  def destroy
    @inventory = Inventory.destroy(params[:id])

    if @inventory.destroyed?
      redirect_to inventories_path, notice: 'Successfully deleted inventory.'
    else
      render :new, alert: 'Could not delete inventory.'
    end
  end

  private

  def inventory_params
    inventory_hash = params.require(:inventory).permit(:name, :description)
    inventory_hash[:user] = current_user
    inventory_hash
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_button.html.erb
<div class="container">
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    Create New
</button>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <%= form_with model: Inventory.new, local: true do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel"><%= form.text_field :name, placeholder: 'Inventory name', class: 'form-control' %></h5>      
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, placeholder: 'Add description', class: "form-control" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Inventory", class: 'btn btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/inventories/_inventory.html.erb
<% @inventories.each do |inventory| %>
  <div class=" card mb-3 mt-3">
  <div class="row g-0">
    <div class="col-md-4 d-flex flex-column align-items-center justify-content-around">
      <h3 class="card-title text-center"><%= inventory.name %></h3>
      <%= link_to 'Remove', inventory_path(inventory), method: :delete , class: "align-text-bottom btn btn-secondary" %>
    </div>
    <div class="col-md-8">
      <div class="card-body d-flex flex-column align-items-center justify-content-around">
        <p class="card-text"><%= inventory.description %></p>
        <%=  link_to 'Check Inventory', inventory_inventory_foods_path(inventory.id), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/inventories/_modal.html.erb
<div class="container">
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
    New Inventory
</button>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
    <%= form_with model: Inventory.new, local: true do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel"><%= form.text_field :name, placeholder: 'Inventory name', class: 'form-control' %></h5>      
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, placeholder: 'Add description', class: "form-control" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <%= form.submit "Inventory", class: 'btn btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>
</div>

app/views/inventories/index.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <h1>Your Inventories</h1>
  <% if current_user %>
    <%= link_to "New Inventory", new_inventory_path, class: "btn btn-primary align-self-end" %> <!-- No layout design, it will look better on navbar -->
    <% if @inventories.empty? %>
      <div>
        <h3 class="text-center">No inventories yet.</h3>
      </div>
    <% else %>
      <% @inventories.each do |inventory| %>
        <div class="d-flex justify-content-center align-items-baseline gap-5 bg-light border w-75 m-auto p-3 my-3">
          <div class="d-flex flex-column align-items-center flex-grow-1">
            <h3 class="text-center"><%= link_to inventory.name, inventory_path(id: inventory.id), class: "text-dark" %></h3>
            <%= link_to "REMOVE", inventory_path(id: inventory.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </div>
          <div class="flex-grow-1" style="max-height: 200px; overflow: auto">
            <p><%= inventory.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/inventories/new.html.erb
<div class="container d-flex flex-column align-items-center">
  <h2>Add new inventory</h2>
  <%= turbo_frame_tag @inventory do %>
    <%= form_with model: @inventory do |form| %>
      <% if @inventory.errors.any? %>
        <div class="alert alert-danger mt-4" role="alert">
          <% @inventory.errors.full_messages.each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      <% end %>
      <div class="form-group mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" , required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", required: true %>
      </div>
      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/inventories/show.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <%if @inventory.user == current_user %>
    <h1><%= @inventory.name %></h1>
    <%= link_to "Add food", new_inventory_inventory_food_path(inventory_id: @inventory.id), class: "btn btn-primary m-1 align-self-end" %>
    <ul class="list-group border mx-0 mt-5 w-75">
      <li class="row align-items-center p-2 bg-secondary text-white border-bottom mx-0">
        <div class="col font-weight-bold text-capitalize"><b>Food</b></div>
        <div class="col font-weight-bold text-capitalize"><b>Quantity</b></div>
        <div class="col font-weight-bold text-capitalize"><b>Actions</b></div>
      </li>
      <% if @inventory_foods.empty? %>
        <h4 class="mt-5">No foods added yet.</h4>
      <% else %>
        <% @inventory_foods.each do | inventory_food | %>
          <li class="row align-items-center p-2 border-bottom border-left border-right mx-0">
            <div class="col"><%= inventory_food.food.name %></div>
            <div class="col"><%= inventory_food.quantity %></div>
            <div class="col">
              <%= link_to "Remove", inventory_inventory_food_path(inventory_id: @inventory.id, id: inventory_food.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
  <% else %>
    <h4 class="mt-5">You are not authorized to see this inventory.</h4>
  <% end %>
</div>