config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[index show new create destroy]

  # Defines the root path route ("/")
  root "home#index"

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end
  resources :inventories, only: %i[index show new create destroy] do
    resources :inventory_foods, only: %i[new create destroy]
  end
  resources :shopping_lists, only: %i[index]

  get '/public_recipes', to: 'recipes#public_recipes'
end

app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id               :bigint           not null, primary key
#  cooking_time     :integer
#  description      :text
#  name             :string
#  preparation_time :integer
#  public           :boolean
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_recipes_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods

  validates :name, presence: true
  validates :preparation_time, numericality: { in: 1..1440 }
  validates :cooking_time, numericality: { in: 1..1440 }
  validates :description, length: { in: 1..200 }
  validates :public, exclusion: [nil]
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, only: %i[index new create destroy]

  load_and_authorize_resource

  def index
    @recipes = Recipe.where(user_id: current_user&.id)
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @recipe_foods = RecipeFood.where(recipe_id: params[:id]).includes([:food])
  end

  def new
    if current_user
      @recipe = Recipe.new
    else
      redirect_to root_path, alert: 'You need to login in order to create a recipe.'
    end
  end

  def create
    @recipe = Recipe.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, notice: 'Successfully created recipe.'
    else
      render :new, alert: 'Could not create recipe.'
    end
  end

  def destroy
    @recipe = Recipe.destroy(params[:id])

    if @recipe.destroyed?
      redirect_to recipes_path, notice: 'Successfully deleted recipe.'
    else
      render :new, alert: 'Could not delete recipe.'
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  private

  def recipe_params
    recipe_hash = params.require(:recipe).permit(:name, :description, :cooking_time, :preparation_time, :public)
    recipe_hash[:user] = current_user
    recipe_hash
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def total_food_items(recipe_id)
    @sub_total = [0, 0]
    if (@recipe_foods = RecipeFood.where(recipe_id: recipe_id))
      @recipe_foods.each do |recipe_food|
        @sub_total[0] += recipe_food.quantity
        @food = Food.find_by(id: recipe_food.food_id)
        @sub_total[1] += @food.price * recipe_food.quantity
      end
    end
    @sub_total
  end

  def total_price(id)
    recipe_food = RecipeFood.find_by(id: id)
    food = Food.find_by(id: recipe_food.food_id)
    recipe_food.quantity * food.price.to_i
  end
end

app/views/recipes/index.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <h1>Your Recipes</h1>
  <% if current_user %>
    <%= link_to "New Recipe", new_recipe_path, class: "btn btn-primary align-self-end" %> <!-- No layout design, it will look better on navbar -->
    <% if @recipes.empty? %>
      <div>
        <h3 class="text-center">No recipes yet.</h3>
      </div>
    <% else %>
      <% @recipes.each do |recipe| %>
        <div class="d-flex justify-content-center align-items-baseline gap-5 bg-light border w-75 m-auto p-3 my-3">
          <div class="d-flex flex-column align-items-center flex-grow-1">
            <h3 class="text-center"><%= link_to recipe.name, recipe_path(id: recipe.id), class: "text-dark" %></h3>
            <%= link_to "REMOVE", recipe_path(id: recipe.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
          </div>
          <div class="flex-grow-1" style="max-height: 200px; overflow: auto">
            <p><%= recipe.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/recipes/new.html.erb
<div class="container d-flex flex-column align-items-center">
  <h2>Add new recipe:</h2>
  <%= turbo_frame_tag @recipe do %>
    <%= form_with model: @recipe do |form| %>
      <% if @recipe.errors.any? %>
        <div class="alert alert-danger mt-4" role="alert">
          <% @recipe.errors.full_messages.each do |message| %>
            <div><%= message %></div>
          <% end %>
        </div>
      <% end %>
      <div class="form-group mb-3">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" , required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :cooking_time %>
        <%= form.number_field :cooking_time, step: 1, class: "form-control", required: true %>
      </div>

      <div class="form-group mb-3">
        <%= form.label :preparation_time %>
        <%= form.number_field :preparation_time, step: 1, class: "form-control", required: true %>
      </div>

      <div class="form-check form-switch mb-3">
        <%= form.label :public, class: "form-check-label" %>
        <%= form.check_box :public, class: "form-check-input" %>
      </div>

      <%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %>
    <% end %>
  <% end %>
</div>

app/views/recipes/public_recipes.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <h1>Public Recipes</h1>
  <% if @recipes.empty? %>
    <h1>No public recipes yet.</h1>
  <% else %>
    <% @recipes.each do |recipe| %>
      <div class="d-flex justify-content-center align-items-baseline gap-5 bg-light border w-75 m-auto p-3 my-3">
        <div class="d-flex flex-column align-items-center flex-grow-1">
          <h3 class="text-center"><%= link_to recipe.name, recipe_path(id: recipe.id), class: "text-dark" %></h3>
          <p class="lead">By: <%= recipe.user.name %></p>
        </div>
        <div class="flex-grow-1" style="max-height: 200px; overflow: auto">
          <% total_food_items(recipe.id) %>
          <p class="lead">Total food items: <%= @sub_total[0] %></p>
          <p class="lead">Total price: $<%= @sub_total[1] %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container mt-3 d-flex flex-column align-items-center">
  <% if @recipe.public || @recipe.user == current_user %>
  <h1><%= @recipe.name %></h1>
  <div class="d-flex flex-column">
    <div class="d-flex align-items-baseline gap-5">
      <p class="fs-5">Preparation time: <%= @recipe.preparation_time %> minutes</p>
      <div class="d-flex align-items-center gap-3">
        <span class="fs-5">Public</span>
        <% if @recipe.public %>
          <i class="bi bi-toggle-on text-success fs-2"></i>
        <% else %>
          <i class="bi bi-toggle-off fs-2"></i>
        <% end %>
      </div>
    </div>
    <p class="fs-5">Cooking time: <%= @recipe.cooking_time %> minutes</p>
    <p class="fs-5">Steps go here...</p>
  </div>
  <div class="d-flex justify-content-between w-50 flex-wrap">
    <button type="button"
      class="btn btn-primary"
      data-bs-toggle="modal"
      data-bs-target="#staticBackdrop">
        Generate shopping list
    </button>
    <%= link_to "Add ingredient", new_recipe_recipe_food_path(recipe_id: @recipe.id), class: "btn btn-primary m-1" if @recipe.user == current_user %>
  </div>
  <% else %>
    <h1>You are not authorized to see this recipe.</h1>
  <% end %>
  <% if @recipe_foods.empty? %>
    <h4 class="mt-5">No foods added yet.</h4>
  <% else %>
    <ul class="list-group border mx-0 mt-5 w-75">
        <li class="row align-items-center p-2 bg-secondary text-white border-bottom mx-0">
          <div class="col font-weight-bold text-capitalize"><b>Food</b></div>
          <div class="col font-weight-bold text-capitalize"><b>Quantity</b></div>
          <div class="col font-weight-bold text-capitalize"><b>Value</b></div>
          <div class="col font-weight-bold text-capitalize"><b>Actions</b></div>
        </li>
        <% @recipe_foods.each do | recipe_food | %>
          <li class="row align-items-center p-2 border-bottom border-left border-right mx-0">
            <div class="col"><%= recipe_food.food.name %></div>
            <div class="col"><%= recipe_food.quantity %></div>
            <div class="col">$<%= total_price(recipe_food.id) %></div>
            <div class="col">
              <%= link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), class: "btn btn-dark" %>
              <%= link_to "Remove", recipe_recipe_food_path(recipe_id: @recipe.id, id: recipe_food.id), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </div>
          </li>
        <% end %>
      </ul>
  <% end %>
</div>

<div class="modal fade"
  id="staticBackdrop"
  data-bs-backdrop="static"
  data-bs-keyboard="false"
  tabindex="-1"
  aria-labelledby="staticBackdropLabel"
  aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Generating Shopping List</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <h6>Choose an inventory to use</h6>
        <%= form_with url: shopping_lists_path, method: :get do |form| %>
          <%= select("inventory", "inventory_id", Inventory.all.collect { |p| [ p.name, p.id ] }, { prompt: 'Select Inventory' }) %>
          <div class="field form-group mb-3">
            <%= form.number_field :recipe_id, class: "form-control", value: @recipe.id, hidden: true %>
          </div>
      <div class="modal-footer">
        <%= form.submit "Generate", data: { turbo: false }, class: "btn btn-primary" %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>