config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[index show new create destroy]

  # Defines the root path route ("/")
  root "home#index"

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end
  resources :inventories, only: %i[index show new create destroy] do
    resources :inventory_foods, only: %i[new create destroy]
  end
  resources :shopping_lists, only: %i[index]

  get '/public_recipes', to: 'recipes#public_recipes'
end

app/models/food.rb
# == Schema Information
#
# Table name: foods
#
#  id               :bigint           not null, primary key
#  measurement_unit :string           not null
#  name             :string           not null
#  price            :decimal(, )      default(0.0)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  user_id          :bigint           not null
#
# Indexes
#
#  index_foods_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Food < ApplicationRecord
  belongs_to :user
  has_many :inventory_foods, dependent: :delete_all
  has_many :recipe_foods, dependent: :delete_all

  validates :name, presence: true
  validates :measurement_unit, presence: true
  validates :price, comparison: { greater_than: 0.0 }, numericality: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @foods = Food.all
  end

  def show
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to foods_path, notice: 'Food created successfully!' }
      else
        format.html { render action: 'new', alert: 'Something went wrong! Food was not created!' }
      end
    end
  end

  def destroy
    @food = Food.find(params[:id]).destroy

    if @food.destroyed?
      redirect_to foods_path, notice: 'Food successfully deleted!'
    else
      redirect_to foods_path, alert: 'Food is not deleted!'
    end
  end

  private

  def food_params
    food_hash = params.require(:food).permit(:name, :measurement_unit, :price)
    food_hash[:user] = current_user
    food_hash
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/views/foods/_form.html.erb
<div class="container d-flex flex-column align-items-center">
  <h2>Add new food</h2>
  <%= form_with model: @food do |form| %>
    <% if @food.errors.any? %>
      <div class="alert alert-danger mt-4" role="alert">
        <% @food.errors.full_messages.each do |message| %>
          <div><%= message %></div>
        <% end %>
      </div>
    <% end %>

    <div class="form-group mb-3">
      <%= form.label :name %> <br>
      <%= form.text_field :name %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :measurement_unit %> <br>
      <%= form.text_field :measurement_unit %>
    </div>

    <div class="form-group mb-3">
      <%= form.label :price %> <br>
      <%= form.number_field :price, step: 0.01 %>
    </div>
    <p><%= form.submit "Create", data: { turbo: false }, class: "btn btn-primary" %></p>
  <% end %>
</div>

app/views/foods/index.html.erb
<section class="d-flex flex-column container">
  <%= link_to "Add Food", new_food_path, class: "btn btn-primary align-self-end" %>
  <%if @foods.present? %>
    <ul class="list-group border mx-0 mt-3">
      <li class="row align-items-center p-2 bg-secondary text-white border-bottom mx-0">
        <div class="col font-weight-bold text-capitalize"><b>Food</b></div>
        <div class="col font-weight-bold text-capitalize"><b>Measurement Unit</b></div>
        <div class="col font-weight-bold text-capitalize"><b>Price</b></div>
        <div class="col font-weight-bold text-capitalize"><b>Actions</b></div>
      </li>
      <% @foods.each do | food | %>
        <li class="row align-items-center p-2 border-bottom border-left border-right mx-0">
          <div class="col"><%= food.name %></div>
          <div class="col"><%= food.measurement_unit %></div>
          <div class="col"><%= food.price %></div>
          <div class="col">
            <%= button_to "Delete", food_path(food), class: "btn btn-danger", method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <div class="border-2">
      <p class="bg-light text-center"> There are no registered foods, yet.
    </div>
  <% end %>
</section>

app/views/foods/new.html.erb
<section class="container">
  <%= render 'foods/form' %>
</section>

app/views/foods/show.html.erb
<h1>Foods#show</h1>
<p>Name: <%= @food.name %></p>
<p>Measurement Unit: <%= @food.measurement_unit %></p>
<p>Price: <%= @food.price %></p>