config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :foods, only: %i[index show new create destroy]

  # Defines the root path route ("/")
  root "home#index"

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: %i[new create edit update destroy]
  end
  resources :inventories, only: %i[index show new create destroy] do
    resources :inventory_foods, only: %i[new create destroy]
  end
  resources :shopping_lists, only: %i[index]

  get '/public_recipes', to: 'recipes#public_recipes'
end

app/views/layouts/_header.html.erb
<nav class="navbar d-flex flex-row justify-content-between navbar-expand-lg navbar-dark bg-dark px-5">
  <div class="container-fluid d-flex">
    <%= link_to "Recipe App", root_path, class: "navbar-brand flex-fill" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end align-items-baseline" id="navbarSupportedContent">
      <% if user_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Recipes", recipes_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Foods", foods_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= link_to "Inventories", inventories_path, class: "nav-link" %>
        </li>
      </ul>
      <% end %>
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0m align-items-baseline">
      <% if user_signed_in? %>
        <li class="nav-item px-4">
          <p class="text-secondary">User: <%= current_user.name %></p>
        </li>
        <li class="nav-item">
          <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-warning mb-1" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <main class="container my-5">
      <%= render "shared/flash" %>
      <%= yield %>
    </main>
  </body>
</html>